"""
SafeGirl — DistilBERT Classifier + Knowledge Base Retrieval Service
=====================================================================

Loads the V3 DistilBERT checkpoint and exposes intent classification
through a small HTTP API, plus semantic retrieval over the SafeGirl
knowledge base.

Architecture
------------
The classifier and retriever run as a standalone Python/FastAPI service:

    Express backend
          |
          | POST /classify
          | POST /retrieve
          v
    FastAPI classifier + retrieval service
          |              |
          v              v
    V3 DistilBERT   multilingual-e5-small
      model          KB embeddings
          |              |
          v              v
    Intent + confidence   Ranked KB passages

The Express backend does not load or execute the PyTorch model directly.

Running locally
---------------
    uvicorn app:app --host 0.0.0.0 --port 8001

The model checkpoint directory is configured through the MODEL_DIR
environment variable. The knowledge base file is configured through
the KB_PATH environment variable.

Example:
    MODEL_DIR=./final KB_PATH=./knowledge_base.json uvicorn app:app --host 0.0.0.0 --port 8001

The checkpoint directory must contain the model and tokenizer files
produced by the V3 final training run, including files such as:

    config.json
    model.safetensors
    tokenizer_config.json
    tokenizer.json

The knowledge base file is generated by build_kb.py from the markdown
sources in resources/knowledge_base/ — see that script rather than
editing knowledge_base.json by hand.

Notes
-----
- SafetyNet is intentionally NOT implemented here. It remains a
  separate deterministic safety layer in the SafeGirl backend.
- The model's own id2label configuration is used rather than assuming
  a hard-coded numerical label ordering.
- Inference uses the same maximum sequence length as V3 training —
  confirm MAX_LENGTH against the actual V3 training config before
  relying on this in production; it was carried over unchanged from V2
  and has not yet been independently verified against V3.
- Retrieval is class-scoped: the classifier's predicted intent narrows
  which KB entries are eligible, so a pregnancy-classified query can't
  retrieve contraception passages. Retrieval degrading gracefully on a
  thin KB (currently 8 entries) is expected, not a bug.
"""

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

import torch
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
)

from retrieval import KnowledgeBaseRetriever


# ============================================================================
# Configuration
# ============================================================================

MODEL_DIR = Path(os.environ.get("MODEL_DIR", "./final"))

MODEL_VERSION = os.environ.get("MODEL_VERSION", "v3")

# Carried over from V2 — confirm this still matches V3's training config
# before trusting it (see module docstring).
MAX_LENGTH = 64

MAX_INPUT_CHARS = 2_000

EXPECTED_LABELS = {
    "contraception",
    "sti",
    "pregnancy",
    "general",
}

# Generated by build_kb.py from resources/knowledge_base/*.md — see that
# script rather than editing this file by hand.
KB_PATH = Path(os.environ.get("KB_PATH", "./knowledge_base.json"))


# ============================================================================
# Logging
# ============================================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

logger = logging.getLogger("safegirl-classifier")


# ============================================================================
# Runtime state
# ============================================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model = None
tokenizer = None
retriever: Optional[KnowledgeBaseRetriever] = None


# ============================================================================
# API schemas
# ============================================================================

class ClassifyRequest(BaseModel):
    """Request body accepted by the /classify endpoint."""

    text: str = Field(
        ...,
        min_length=1,
        description="User query to classify.",
    )


class ClassifyResponse(BaseModel):
    """Classification result returned by the /classify endpoint."""

    intent: str = Field(
        description="Predicted SafeGirl intent category.",
    )

    confidence: float = Field(
        description="Softmax score of the predicted intent.",
        ge=0.0,
        le=1.0,
    )

    scores: dict[str, float] = Field(
        description="Softmax score for every supported intent.",
    )


class RetrieveRequest(BaseModel):
    """Request body accepted by the /retrieve endpoint."""

    query: str = Field(
        ...,
        min_length=1,
        description="User query to retrieve knowledge-base passages for.",
    )

    top_k: int = Field(
        default=3,
        ge=1,
        description="Maximum number of passages to return.",
    )

    intent: Optional[str] = Field(
        default=None,
        description=(
            "Optional class filter, typically the intent returned by "
            "/classify (e.g. 'sti', 'contraception'). When set, only "
            "knowledge-base entries of that class are considered."
        ),
    )


class RetrieveResult(BaseModel):
    """A single ranked knowledge-base passage."""

    id: str
    class_: str = Field(alias="class")  # 'class' is a reserved word in Python
    title: str
    content: str
    source: str
    score: float

    class Config:
        populate_by_name = True


class RetrieveResponse(BaseModel):
    """Response body returned by the /retrieve endpoint."""

    results: list[RetrieveResult]


# ============================================================================
# Model loading
# ============================================================================

def validate_model_labels(loaded_model) -> None:
    """
    Validate that the checkpoint contains the four expected SafeGirl
    intent categories.

    The numerical ordering of labels is deliberately not hard-coded.
    The mapping stored inside the trained checkpoint remains authoritative.
    """

    raw_id2label = loaded_model.config.id2label

    labels = {
        str(label).strip().lower()
        for label in raw_id2label.values()
    }

    if labels != EXPECTED_LABELS:
        raise RuntimeError(
            "Model label configuration does not match the expected "
            f"SafeGirl V3 categories. Expected {sorted(EXPECTED_LABELS)}, "
            f"but found {sorted(labels)}."
        )


def load_model() -> None:
    """
    Load the tokenizer and trained classifier checkpoint into memory.

    This function is called once when the FastAPI application starts.
    Loading the model once avoids repeatedly reading the checkpoint
    from disk for every classification request.
    """

    global model, tokenizer

    if not MODEL_DIR.exists():
        raise RuntimeError(
            f"MODEL_DIR '{MODEL_DIR}' does not exist. "
            "Set MODEL_DIR to the SafeGirl V3 final checkpoint directory."
        )

    if not MODEL_DIR.is_dir():
        raise RuntimeError(
            f"MODEL_DIR '{MODEL_DIR}' is not a directory: {MODEL_DIR}"
        )

    logger.info(
        "Loading SafeGirl classifier model from '%s' onto %s.",
        MODEL_DIR,
        DEVICE,
    )

    try:
        tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)

        model = AutoModelForSequenceClassification.from_pretrained(
            MODEL_DIR
        )

        validate_model_labels(model)

        model.to(DEVICE)
        model.eval()

    except Exception as exc:
        # Do not leave a partially initialized model available.
        model = None
        tokenizer = None

        raise RuntimeError(
            f"Failed to load SafeGirl classifier from '{MODEL_DIR}'."
        ) from exc

    logger.info(
        "SafeGirl V3 classifier loaded successfully."
    )

    logger.info(
        "Model labels: %s",
        model.config.id2label,
    )


def load_retriever() -> None:
    """
    Load the knowledge-base retriever into memory.

    This function is called once when the FastAPI application starts,
    alongside load_model(). A failure here does not fall back to
    partial retriever state — the retriever is left as None so /retrieve
    fails loudly (503) rather than silently returning nothing.
    """

    global retriever

    logger.info(
        "Loading SafeGirl knowledge-base retriever from '%s'.",
        KB_PATH,
    )

    try:
        retriever = KnowledgeBaseRetriever(KB_PATH)
    except Exception as exc:
        retriever = None

        raise RuntimeError(
            f"Failed to load SafeGirl knowledge base from '{KB_PATH}'."
        ) from exc

    logger.info(
        "SafeGirl knowledge-base retriever loaded successfully."
    )


# ============================================================================
# FastAPI application lifecycle
# ============================================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI application lifecycle.

    The model and retriever are loaded once during application startup
    and remain available for subsequent requests.
    """

    load_model()
    load_retriever()

    yield

    # Release references during application shutdown.
    global model, tokenizer, retriever
    model = None
    tokenizer = None
    retriever = None

    logger.info("SafeGirl classifier service shut down.")


app = FastAPI(
    title="SafeGirl Classifier + Retrieval Inference Service",
    description=(
        "Inference API for the SafeGirl V3 multilingual DistilBERT "
        "intent classifier and knowledge-base retrieval."
    ),
    version=MODEL_VERSION,
    lifespan=lifespan,
)


# ============================================================================
# Health endpoint
# ============================================================================

@app.get("/health")
def health() -> dict[str, str]:
    """
    Return service health and model information.

    This endpoint can be used by the Express backend or deployment
    tooling to determine whether the classifier service is available.
    """

    if model is None:
        return {
            "status": "model_not_loaded",
            "device": str(DEVICE),
            "model_version": MODEL_VERSION,
        }

    return {
        "status": "ok",
        "device": str(DEVICE),
        "model_version": MODEL_VERSION,
    }


# ============================================================================
# Classification endpoint
# ============================================================================

@app.post(
    "/classify",
    response_model=ClassifyResponse,
)
def classify(request: ClassifyRequest) -> ClassifyResponse:
    """
    Classify one SafeGirl user query.

    The trained model returns:
        - the predicted intent,
        - its softmax confidence score,
        - scores for all supported intent categories.
    """

    if model is None or tokenizer is None:
        raise HTTPException(
            status_code=503,
            detail="Classifier model is not loaded.",
        )

    text = request.text.strip()

    if not text:
        raise HTTPException(
            status_code=400,
            detail="text must be non-empty.",
        )

    if len(text) > MAX_INPUT_CHARS:
        raise HTTPException(
            status_code=400,
            detail=(
                f"text exceeds the maximum allowed length of "
                f"{MAX_INPUT_CHARS} characters."
            ),
        )

    # Tokenization settings intentionally match the V3 training pipeline.
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=MAX_LENGTH,
    )

    # Move tokenized tensors to the same device as the model.
    inputs = {
        key: value.to(DEVICE)
        for key, value in inputs.items()
    }

    # Inference does not require gradient computation.
    # inference_mode() is optimized for inference workloads.
    with torch.inference_mode():
        logits = model(**inputs).logits
        probabilities = torch.softmax(logits, dim=-1)[0]

    # The checkpoint's own label mapping is authoritative.
    id2label = {
        int(index): str(label).lower()
        for index, label in model.config.id2label.items()
    }

    scores = {
        id2label[index]: float(probabilities[index])
        for index in range(len(probabilities))
    }

    predicted_id = int(
        torch.argmax(probabilities).item()
    )

    predicted_intent = id2label[predicted_id]
    confidence = float(probabilities[predicted_id])

    return ClassifyResponse(
        intent=predicted_intent,
        confidence=confidence,
        scores=scores,
    )


# ============================================================================
# Retrieval endpoint
# ============================================================================

@app.post(
    "/retrieve",
    response_model=RetrieveResponse,
)
def retrieve(request: RetrieveRequest) -> RetrieveResponse:
    """
    Retrieve knowledge-base passages relevant to one SafeGirl user query.

    When request.intent is set (normally the intent /classify already
    returned for this query), retrieval is scoped to that class only.
    Retrieval degrades gracefully on a thin knowledge base — a class
    with zero eligible entries returns an empty result list rather than
    raising.
    """

    if retriever is None:
        raise HTTPException(
            status_code=503,
            detail="Knowledge-base retriever is not loaded.",
        )

    query = request.query.strip()

    if not query:
        raise HTTPException(
            status_code=400,
            detail="query must be non-empty.",
        )

    if len(query) > MAX_INPUT_CHARS:
        raise HTTPException(
            status_code=400,
            detail=(
                f"query exceeds the maximum allowed length of "
                f"{MAX_INPUT_CHARS} characters."
            ),
        )

    results = retriever.retrieve(
        query=query,
        top_k=request.top_k,
        class_filter=request.intent,
    )

    return RetrieveResponse(results=[
        RetrieveResult(**r) for r in results
    ])


# ============================================================================
# Local development entry point
# ============================================================================

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app:app",
        host="0.0.0.0",
        port=8001,
        reload=False,
    )