"""
SafeGirl -- knowledge base retrieval
======================================

Cross-lingual semantic retrieval over the SafeGirl knowledge base using
intfloat/multilingual-e5-small. This model's convention requires prefixing
inputs with "query: " or "passage: " depending on role -- queries and
passages are NOT interchangeable inputs, this prefixing is required for
the model to produce comparable embeddings (see the model card).

Cosine similarity is computed via a plain dot product because embeddings
are normalized at encode time (normalize_embeddings=True) -- for unit
vectors, dot product IS cosine similarity, this is not an approximation.

Status: the knowledge base this reads from is generated by build_kb.py
from the markdown sources in resources/knowledge_base/ -- see that
script rather than editing the generated JSON by hand. This
module is retrieval mechanics only; it does not vouch for the content
it retrieves.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np
from sentence_transformers import SentenceTransformer

logger = logging.getLogger(__name__)

EMBEDDING_MODEL_NAME = "intfloat/multilingual-e5-small"
QUERY_PREFIX = "query: "
PASSAGE_PREFIX = "passage: "

REQUIRED_FIELDS = {"id", "class", "title", "content", "source"}


class KnowledgeBaseRetriever:
    """Loads the knowledge base once at startup, embeds every passage
    once, and answers retrieve() calls by cosine similarity against the
    precomputed passage embeddings. Re-embedding on every request would
    be wasteful and slow -- passage embeddings are fixed until the KB
    file changes, so this is a one-time cost paid at construction."""

    def __init__(self, kb_path: str | Path):
        self.kb_path = Path(kb_path)
        if not self.kb_path.exists():
            raise FileNotFoundError(f"Knowledge base file not found: {self.kb_path}")

        with self.kb_path.open("r", encoding="utf-8") as f:
            self.entries: list[dict] = json.load(f)

        if not self.entries:
            raise RuntimeError(f"Knowledge base file is empty: {self.kb_path}")

        for i, entry in enumerate(self.entries):
            missing = REQUIRED_FIELDS - entry.keys()
            if missing:
                raise ValueError(
                    f"KB entry {i} (id={entry.get('id', '?')}) missing "
                    f"required fields: {sorted(missing)}"
                )

        ids = [e["id"] for e in self.entries]
        if len(ids) != len(set(ids)):
            dupes = {i for i in ids if ids.count(i) > 1}
            raise ValueError(f"Duplicate KB entry ids: {dupes}")

        logger.info(f"Loading embedding model: {EMBEDDING_MODEL_NAME}")
        self.model = SentenceTransformer(EMBEDDING_MODEL_NAME)

        passages = [
            PASSAGE_PREFIX + e["title"] + ". " + e["content"]
            for e in self.entries
        ]
        self.embeddings = self.model.encode(
            passages, convert_to_numpy=True, normalize_embeddings=True
        )

        # class -> list of indices into self.entries / self.embeddings,
        # so class-scoped retrieval doesn't need to rescan every entry.
        self.class_index: dict[str, list[int]] = {}
        for i, entry in enumerate(self.entries):
            self.class_index.setdefault(entry["class"], []).append(i)

        logger.info(
            f"Knowledge base loaded: {len(self.entries)} entries across "
            f"{len(self.class_index)} classes: "
            f"{ {k: len(v) for k, v in self.class_index.items()} }"
        )

    def retrieve(
        self,
        query: str,
        top_k: int = 3,
        class_filter: str | None = None,
    ) -> list[dict]:
        """Returns up to top_k KB entries ranked by cosine similarity to
        the query, each annotated with a 'score' field. If class_filter
        is given, only entries of that class are considered -- this is
        the normal path from app.py, since the classifier already tells
        us the query's intent, and there's no reason to let e.g. a
        pregnancy-classified query retrieve contraception passages.

        If class_filter names a class with zero entries, or the KB has
        fewer than top_k eligible entries, this returns whatever is
        available rather than erroring -- retrieval degrading gracefully
        on a thin KB is expected right now (see README's known
        limitation), not a bug to raise on.
        """
        if class_filter is not None:
            candidate_indices = self.class_index.get(class_filter, [])
            if not candidate_indices:
                logger.warning(
                    f"No KB entries for class_filter={class_filter!r} -- "
                    "returning empty result."
                )
                return []
        else:
            candidate_indices = list(range(len(self.entries)))

        query_emb = self.model.encode(
            QUERY_PREFIX + query, convert_to_numpy=True, normalize_embeddings=True
        )

        candidate_embeddings = self.embeddings[candidate_indices]
        scores = candidate_embeddings @ query_emb  # cosine sim, unit vectors

        ranked_local = np.argsort(-scores)[:top_k]

        results = []
        for local_idx in ranked_local:
            global_idx = candidate_indices[local_idx]
            entry = self.entries[global_idx]
            results.append({
                "id": entry["id"],
                "class": entry["class"],
                "title": entry["title"],
                "content": entry["content"],
                "source": entry["source"],
                "score": float(scores[local_idx]),
            })
        return results